"""
DeployGTM — Company Research + ICP Fit Scoring

For each account in the matrix that hasn't been researched yet (or --force),
this script:
  1. Pulls firmographic data via Apollo enrich_company
  2. Fetches a short web snapshot of the company's site
  3. Asks Claude to evaluate ICP fit against the dimensions defined in the
     client's ICP profile (projects/deploygtm-own/data/<client>_icp_profile.json)
  4. Writes fit_score + research fields back to accounts.json
  5. Triggers score_engine.apply_score so current_score is immediately updated

CLIENT-AGNOSTIC
  The fit dimensions are NOT hardcoded. They come from the client's ICP
  profile, generated by `make derive-icp CLIENT=<slug>`. If no profile
  exists, falls back to universal default dimensions.

Usage:
  python projects/deploygtm-own/scripts/research_accounts.py \\
      --client deploygtm --tier 1,2

  # Force re-research even if already researched
  python projects/deploygtm-own/scripts/research_accounts.py \\
      --client peregrine-space --company "Acme Defense" --force
"""

from __future__ import annotations

import json
import os
import re
import sys
import time
from datetime import date
from pathlib import Path
from typing import Optional

import click
import requests

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.resolve().parents[2]

if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))
if str(REPO_ROOT / "scripts") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "scripts"))

try:
    from dotenv import load_dotenv
    load_dotenv(REPO_ROOT / ".env")
except ImportError:
    pass

from generate_outreach import _matrix_path, load_client_matrix, find_account  # noqa: E402
from score_engine import set_fit_score  # noqa: E402
from derive_icp import load_profile, profile_path  # noqa: E402


# ─── Web snapshot ─────────────────────────────────────────────────────────────

_HTML_TAG = re.compile(r"<[^>]+>")
_WHITESPACE = re.compile(r"\s{2,}")
_FETCH_TIMEOUT = 8
_FETCH_PATHS = ["/", "/about", "/product", "/pricing"]


def _fetch_web_snapshot(domain: str, max_chars: int = 3000) -> str:
    """Return stripped text from the company's homepage (best-effort)."""
    base = domain.rstrip("/")
    if not base.startswith("http"):
        base = f"https://{base}"

    headers = {"User-Agent": "Mozilla/5.0 (compatible; DeployGTM-research/1.0)"}
    chunks: list[str] = []

    for path in _FETCH_PATHS:
        if sum(len(c) for c in chunks) >= max_chars:
            break
        try:
            resp = requests.get(f"{base}{path}", headers=headers,
                                timeout=_FETCH_TIMEOUT, allow_redirects=True)
            if resp.status_code == 200:
                text = _HTML_TAG.sub(" ", resp.text)
                text = _WHITESPACE.sub(" ", text).strip()
                chunks.append(text[:1000])
        except Exception:
            continue

    return "\n\n".join(chunks)[:max_chars] if chunks else ""


# ─── Claude research call ──────────────────────────────────────────────────────

_RESEARCH_SYSTEM_TEMPLATE = """\
You are a B2B research analyst evaluating whether a company is a good fit
for a specific client's ICP. The client and their scoring framework are
defined below — you must score against THESE dimensions, not generic ones.

# Client product
{product_summary}

# Fit dimensions to score (each 0–{max_raw})
{dimensions_block}

# Disqualifiers (return fit_score=0 if any apply)
{disqualifiers_block}

You will receive:
- Firmographic data from Apollo (may be partial)
- A short web snapshot (may be empty if blocked)

Respond in valid JSON with EXACTLY these fields:
{{
  "fit_score": <weighted sum, 0–{fit_max_score}, one decimal>,
  "fit_dimensions": {{
{dimension_score_keys}
  }},
  "pain_hypothesis": "<one sentence — most likely pain this company has that the client solves>",
  "fit_rationale": "<two sentences — why this score>",
  "company_profile": {{
    "what_they_do": "<one sentence>",
    "stage": "<seed|series_a|series_b_plus|bootstrap|public|gov_contractor|other|unknown>",
    "employee_count": <integer or null>,
    "tech_stack_signals": ["<signal1>", "<signal2>"],
    "buying_signal": "<observable signal that supports / contradicts buying intent>"
  }},
  "disqualified": <true|false>,
  "confidence": "<high|medium|low>"
}}

Compute fit_score using the per-dimension weights:
  fit_score = sum(dimension_raw_score × dimension_weight) for each dimension

Cap fit_score at {fit_max_score}. If `disqualified` is true, set fit_score to 0.

Label your inferences:
- [confirmed] = from Apollo or official company data
- [researched] = from the web snapshot
- [inferred] = your judgment from partial signals

Output valid JSON only. No prose, no markdown fences.
"""


def _build_system_prompt(profile: dict) -> str:
    """Render the research system prompt from the ICP profile."""
    dims = profile.get("fit_dimensions", [])
    fit_max_score = profile.get("fit_max_score", 10.0)

    dimensions_block = "\n".join(
        f"- {d['name']} (weight {d['weight']}, max raw {d['max_raw']}): "
        f"{d.get('description', '')}\n"
        f"    HIGH ({d['max_raw']}): {d.get('high_signal', '')}\n"
        f"    LOW (0): {d.get('low_signal', '')}"
        for d in dims
    ) or "  (no client dimensions defined — use generic B2B fit judgment)"

    dimension_score_keys = ",\n".join(
        f'    "{d["name"]}": <0–{d["max_raw"]}>'
        for d in dims
    ) or '    "general_fit": <0–10>'

    disqualifiers = profile.get("disqualifiers", [])
    disqualifiers_block = "\n".join(f"- {d}" for d in disqualifiers) \
        or "  (no hard disqualifiers defined)"

    max_raw = max((d.get("max_raw", 2) for d in dims), default=2)

    return _RESEARCH_SYSTEM_TEMPLATE.format(
        product_summary=profile.get("client_product_summary", "(client product not described)"),
        dimensions_block=dimensions_block,
        disqualifiers_block=disqualifiers_block,
        fit_max_score=fit_max_score,
        dimension_score_keys=dimension_score_keys,
        max_raw=max_raw,
    )


def _research_with_claude(
    account: dict,
    firmographics: dict,
    web_snapshot: str,
    profile: dict,
    api_key: Optional[str] = None,
) -> dict:
    """Call Claude to produce fit_score and company profile. Returns parsed dict."""
    import anthropic

    key = api_key or os.environ.get("ANTHROPIC_API_KEY", "")
    if not key:
        raise click.ClickException("ANTHROPIC_API_KEY not set.")

    client_obj = anthropic.Anthropic(api_key=key)

    user_content = f"""Company: {account['company']}
Domain: {account['domain']}

Apollo firmographics:
{json.dumps(firmographics, indent=2)}

Web snapshot:
{web_snapshot or '[no web content retrieved]'}
"""

    msg = client_obj.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=1024,
        system=[
            {
                "type": "text",
                "text": _build_system_prompt(profile),
                "cache_control": {"type": "ephemeral"},
            }
        ],
        messages=[{"role": "user", "content": user_content}],
    )

    raw = msg.content[0].text.strip()
    raw = re.sub(r"^```(?:json)?\s*", "", raw)
    raw = re.sub(r"\s*```$", "", raw)

    return json.loads(raw)


# ─── Per-account research ──────────────────────────────────────────────────────


def research_account(
    account: dict,
    profile: dict,
    dry_run: bool = False,
    verbose: bool = False,
) -> dict:
    """Research one account: Apollo → web → Claude → set fit_score.

    Modifies account in place. Returns the research result dict from Claude.
    """
    domain = account.get("domain", "")
    company = account.get("company", "")

    click.echo(f"  Researching {company} ({domain})...")

    # 1. Apollo firmographics
    firmographics: dict = {}
    try:
        from apollo import enrich_company
        firmographics = enrich_company(domain)
        if verbose:
            click.echo(f"    Apollo: {firmographics.get('industry', '?')}, "
                       f"{firmographics.get('employee_count', '?')} employees, "
                       f"stage={firmographics.get('funding_stage', '?')}")
    except Exception as e:
        click.echo(f"    WARN Apollo enrichment failed: {e}", err=True)

    # 2. Web snapshot
    web_snapshot = ""
    try:
        web_snapshot = _fetch_web_snapshot(domain)
        if verbose:
            click.echo(f"    Web snapshot: {len(web_snapshot)} chars")
    except Exception as e:
        click.echo(f"    WARN web fetch failed: {e}", err=True)

    if dry_run:
        click.echo(f"    (dry-run) skipping Claude call.")
        return {}

    # 3. Claude research using client's ICP profile
    try:
        result = _research_with_claude(account, firmographics, web_snapshot, profile)
    except json.JSONDecodeError as e:
        click.echo(f"    ERROR: Claude returned invalid JSON: {e}", err=True)
        return {}
    except Exception as e:
        click.echo(f"    ERROR: Claude research failed: {e}", err=True)
        return {}

    # 4. Write back to account
    fit_score = float(result.get("fit_score", 0))
    if result.get("disqualified"):
        fit_score = 0.0

    account["fit_score"] = round(min(10.0, max(0.0, fit_score)), 2)
    account["pain_hypothesis"] = result.get("pain_hypothesis", "")
    account["fit_rationale"] = result.get("fit_rationale", "")
    account["fit_dimensions"] = result.get("fit_dimensions", {})
    account["company_profile"] = result.get("company_profile", {})
    account["research_confidence"] = result.get("confidence", "low")
    account["disqualified"] = bool(result.get("disqualified"))
    account["researched_at"] = date.today().isoformat()

    # Update firmographics if Apollo returned data
    if firmographics and not firmographics.get("error"):
        account.setdefault("firmographics", {}).update(firmographics)

    # 5. Recompute score using the client's profile
    set_fit_score(
        account, fit_score,
        rationale=f"research_{date.today().isoformat()}",
        profile=profile,
    )

    click.echo(
        f"    fit_score={account['fit_score']}  "
        f"score={account.get('current_score', '?')}  "
        f"confidence={account['research_confidence']}"
        + ("  [DISQUALIFIED]" if account['disqualified'] else "")
    )

    return result


# ─── Batch runner ─────────────────────────────────────────────────────────────


def research_matrix(
    client: str,
    tiers: Optional[list[int]] = None,
    company_filter: Optional[str] = None,
    force: bool = False,
    dry_run: bool = False,
    verbose: bool = False,
    delay: float = 1.0,
) -> list[str]:
    """Research all matching accounts. Returns list of researched company names."""
    matrix = load_client_matrix(client)
    profile = load_profile(client)

    if not profile_path(client).exists():
        click.echo(
            f"  WARN: no ICP profile at {profile_path(client).name}. "
            f"Using universal defaults — run `make derive-icp CLIENT={client}` "
            f"for client-specific dimensions.",
            err=True,
        )

    researched: list[str] = []

    for account in matrix.get("accounts", []):
        if company_filter and account["company"].lower() != company_filter.lower():
            continue
        if tiers and account.get("icp_tier") not in tiers:
            continue
        if not force and account.get("researched_at"):
            if verbose:
                click.echo(f"  Skipping {account['company']} (researched {account['researched_at']})")
            continue

        research_account(account, profile, dry_run=dry_run, verbose=verbose)
        researched.append(account["company"])

        if delay > 0:
            time.sleep(delay)

    if not dry_run and researched:
        path = _matrix_path(client)
        path.write_text(json.dumps(matrix, indent=2) + "\n")
        click.echo(f"\n  Saved {len(researched)} researched account(s) to {path.name}.")

    return researched


# ─── CLI ─────────────────────────────────────────────────────────────────────


@click.command()
@click.option("--client", required=True, help="Client slug.")
@click.option("--tier", "tier_str", default="1,2", show_default=True,
              help="Comma-separated tier filter (e.g. 1 or 1,2).")
@click.option("--company", "company_filter", default=None,
              help="Research only this company (exact name match).")
@click.option("--force", is_flag=True,
              help="Re-research even if researched_at is already set.")
@click.option("--dry-run", is_flag=True,
              help="Pull Apollo + web data but skip Claude call and writes.")
@click.option("--verbose", "-v", is_flag=True)
@click.option("--delay", default=1.0, show_default=True,
              help="Seconds to wait between Claude calls.")
def main(
    client: str,
    tier_str: str,
    company_filter: Optional[str],
    force: bool,
    dry_run: bool,
    verbose: bool,
    delay: float,
):
    """Research accounts via Apollo + web + Claude and set fit_score."""
    tiers = [int(t.strip()) for t in tier_str.split(",") if t.strip().isdigit()]

    click.echo(f"\nResearching {client} accounts (tiers: {tiers})...")
    if dry_run:
        click.echo("(dry-run mode — no writes)")

    done = research_matrix(
        client=client,
        tiers=tiers,
        company_filter=company_filter,
        force=force,
        dry_run=dry_run,
        verbose=verbose,
        delay=delay,
    )

    click.echo(f"\nDone. Researched {len(done)} account(s).")
    if done:
        click.echo("Next: run `make enrich-contacts` to find key contacts.")


if __name__ == "__main__":
    main()
