"""
DeployGTM — Dynamic ICP Score Engine

Score = fit_score + signal_bonus + status_mod + sentiment_mod

  fit_score     : 0–10 set by research_accounts.py against the client's
                  ICP profile dimensions. Never decays. Falls back to a
                  tier estimate if research hasn't run yet.
  signal_bonus  : signal_weight × 3 × recency_factor. Decays linearly to 0
                  over 2 × per-signal-half-life. 0 when no verified date.
  status_mod    : lifecycle stage contribution (replied/meeting_booked push
                  scores up regardless of signal age)
  sentiment_mod : most-recent variant response sentiment

CLIENT-AGNOSTIC
  All weights, decay rates, and statuses are loaded from the client's
  ICP profile (projects/deploygtm-own/data/<client>_icp_profile.json),
  generated by `make derive-icp CLIENT=<slug>`. Defaults are used if no
  profile exists, so the engine works out of the box.

Score thresholds:
  >= 12  → HOT — activate immediately
  >= 8   → ENGAGE — batch outreach
  >= 4   → WATCH — monitor, not ready
  < 4    → COLD — deprioritise
"""

from __future__ import annotations

import json
import sys
from datetime import date
from pathlib import Path
from typing import Optional

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.resolve().parents[2]

if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))
if str(REPO_ROOT / "scripts") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "scripts"))

from generate_outreach import _matrix_path, load_client_matrix  # noqa: E402

# Load shared default profile + loader (single source of truth)
try:
    from derive_icp import DEFAULT_PROFILE, load_profile  # noqa: E402
except ImportError:
    # Fallback if derive_icp.py is missing — shouldn't happen in practice
    DEFAULT_PROFILE = {}

    def load_profile(client: str) -> dict:  # type: ignore
        return {}


# ─── Threshold constants (independent of profile) ─────────────────────────────

HOT_THRESHOLD = 12
ENGAGEMENT_THRESHOLD = 8
WATCH_THRESHOLD = 4

SIGNAL_MULTIPLIER = 3  # max bonus = SIGNAL_WEIGHT × SIGNAL_MULTIPLIER

# Re-export defaults for callers that don't load a client profile
_DEFAULT = DEFAULT_PROFILE or {}
SIGNAL_WEIGHT: dict = _DEFAULT.get("signal_weights", {
    "funding": 3, "hiring": 2, "leadership_change": 2, "manual": 1,
})
STATUS_DELTA: dict = _DEFAULT.get("status_deltas", {
    "active": 1, "outreach_sent": 2, "replied": 6, "meeting_booked": 12,
    "no_fit": -15, "paused": -3, "monitor": 0,
})
SENTIMENT_DELTA: dict = _DEFAULT.get("sentiment_deltas", {
    "positive": 4, "neutral": 1, "negative": -2,
})
TIER_FIT_FALLBACK: dict = {
    int(k): v for k, v in (_DEFAULT.get("tier_fit_fallback") or {1: 7.0, 2: 4.5, 3: 2.0}).items()
}
DECAY_HALF_LIFE_DAYS = _DEFAULT.get("signal_decay_days", {}).get("default", 60)


# ─── Helpers ──────────────────────────────────────────────────────────────────


def _signal_age_days(signal_date_str: str) -> Optional[int]:
    """Return days since the signal date, or None if absent / VERIFY marker."""
    if not signal_date_str or "VERIFY" in signal_date_str.upper():
        return None
    try:
        d = date.fromisoformat(signal_date_str[:10])
        return max(0, (date.today() - d).days)
    except ValueError:
        return None


def _recency_factor(age_days: Optional[int], half_life_days: int) -> float:
    """Linear decay from 1.0 (fresh) to 0.0 at 2 × half-life. 0 if no date."""
    if age_days is None:
        return 0.0
    max_age = max(1, half_life_days * 2)
    return max(0.0, 1.0 - age_days / max_age)


def _profile_or_default(profile: Optional[dict]) -> dict:
    """Return a usable profile dict — caller's profile, or a hardcoded default."""
    if profile:
        return profile
    if DEFAULT_PROFILE:
        return DEFAULT_PROFILE
    # Last-resort hardcoded fallback
    return {
        "signal_weights": SIGNAL_WEIGHT,
        "signal_decay_days": {"default": DECAY_HALF_LIFE_DAYS},
        "status_deltas": STATUS_DELTA,
        "sentiment_deltas": SENTIMENT_DELTA,
        "tier_fit_fallback": TIER_FIT_FALLBACK,
    }


# ─── Core scoring ─────────────────────────────────────────────────────────────


def compute_score(account: dict, profile: Optional[dict] = None) -> float:
    """Compute the current dynamic score for one account.

    If `profile` is provided, scoring uses its weights/decays/statuses;
    otherwise falls back to DEFAULT_PROFILE. Does NOT modify the account
    dict — call apply_score() to persist.
    """
    p = _profile_or_default(profile)

    signal_weights = p.get("signal_weights", SIGNAL_WEIGHT)
    decay_days_map = p.get("signal_decay_days", {"default": DECAY_HALF_LIFE_DAYS})
    status_deltas = p.get("status_deltas", STATUS_DELTA)
    sentiment_deltas = p.get("sentiment_deltas", SENTIMENT_DELTA)
    tier_fallback_raw = p.get("tier_fit_fallback", TIER_FIT_FALLBACK)
    tier_fallback = {int(k): v for k, v in tier_fallback_raw.items()}

    tier = account.get("icp_tier", 3)
    signal = account.get("why_now_signal", {})
    signal_type = signal.get("type", "manual")
    signal_date = signal.get("date", "")
    status = account.get("status", "monitor")

    # Base: research-derived fit score (never decays)
    fit_score: float = account.get("fit_score") or tier_fallback.get(tier, 2.0)

    # Signal bonus: per-signal decay rate, 0 if no verified date
    half_life = decay_days_map.get(signal_type) or decay_days_map.get("default", 60)
    age_days = _signal_age_days(signal_date)
    recency = _recency_factor(age_days, half_life)
    signal_bonus = signal_weights.get(signal_type, 1) * SIGNAL_MULTIPLIER * recency

    # Status modifier
    status_mod = status_deltas.get(status, 0)

    # Variant sentiment modifier (most recent in history)
    sentiment_mod = 0.0
    for event in reversed(account.get("score_history", [])):
        if event.get("type") == "sentiment":
            sentiment_mod = sentiment_deltas.get(event.get("value", ""), 0)
            break

    raw = fit_score + signal_bonus + status_mod + sentiment_mod
    return round(max(0.0, raw), 2)


def apply_score(account: dict, reason: str = "recalculated", profile: Optional[dict] = None) -> dict:
    """Compute and store current_score + append to score_history."""
    prev = account.get("current_score")
    new_score = compute_score(account, profile=profile)

    account["current_score"] = new_score

    history = account.setdefault("score_history", [])
    entry: dict = {
        "date": date.today().isoformat(),
        "score": new_score,
        "reason": reason,
        "type": "recalculate",
    }
    if prev is not None:
        entry["delta"] = round(new_score - prev, 2)
    history.append(entry)

    return account


def record_event(
    account: dict,
    event_type: str,
    value: str,
    reason: str = "",
    profile: Optional[dict] = None,
) -> dict:
    """Record a score-affecting event and recompute.

    event_type: "sentiment" | "birddog_signal" | "status_change"
    value:      event-specific string (positive/neutral/negative; etc.)
    """
    history = account.setdefault("score_history", [])
    history.append({
        "date": date.today().isoformat(),
        "type": event_type,
        "value": value,
        "reason": reason,
        "score": account.get("current_score"),
    })
    return apply_score(account, reason=reason or f"{event_type}={value}", profile=profile)


def set_fit_score(
    account: dict,
    fit_score: float,
    rationale: str = "",
    profile: Optional[dict] = None,
) -> dict:
    """Set the research-derived fit_score and recompute. Returns account."""
    account["fit_score"] = round(min(10.0, max(0.0, fit_score)), 2)
    history = account.setdefault("score_history", [])
    history.append({
        "date": date.today().isoformat(),
        "type": "fit_score_set",
        "value": account["fit_score"],
        "reason": rationale or "research",
        "score": account.get("current_score"),
    })
    return apply_score(account, reason=f"fit_score={account['fit_score']}", profile=profile)


# ─── Matrix-level operations ──────────────────────────────────────────────────


def score_matrix(client: str, save: bool = True) -> list[dict]:
    """Recompute scores for all accounts in a client matrix.

    Loads the client's ICP profile and applies it to every account.
    Returns list of change dicts for accounts whose score shifted > 0.1.
    """
    matrix = load_client_matrix(client)
    profile = load_profile(client)
    changed = []

    for account in matrix.get("accounts", []):
        old = account.get("current_score")
        apply_score(account, reason="weekly_refresh", profile=profile)
        new = account["current_score"]
        if old is None or abs(new - old) > 0.1:
            changed.append({
                "company": account["company"],
                "domain": account["domain"],
                "old_score": old,
                "new_score": new,
                "status": account.get("status", "monitor"),
                "fit_score": account.get("fit_score"),
            })

    if save:
        path = _matrix_path(client)
        path.write_text(json.dumps(matrix, indent=2) + "\n")

    return changed


def get_prioritized(client: str, min_score: float = 0) -> list[dict]:
    """Return accounts sorted by current_score descending."""
    matrix = load_client_matrix(client)
    profile = load_profile(client)
    accounts = []
    for a in matrix.get("accounts", []):
        score = a.get("current_score") or compute_score(a, profile=profile)
        if score >= min_score:
            accounts.append({**a, "current_score": score})
    return sorted(accounts, key=lambda x: x["current_score"], reverse=True)


def threshold_label(score: float) -> str:
    """Return a human-readable tier label for a score."""
    if score >= HOT_THRESHOLD:
        return "HOT"
    if score >= ENGAGEMENT_THRESHOLD:
        return "ENGAGE"
    if score >= WATCH_THRESHOLD:
        return "WATCH"
    return "COLD"


# ─── CLI ─────────────────────────────────────────────────────────────────────


import click  # noqa: E402


@click.group()
def cli():
    """Dynamic ICP score engine for the account matrix."""
    pass


@cli.command("refresh")
@click.option("--client", required=True, help="Client slug.")
@click.option("--min-delta", default=0.5, show_default=True,
              help="Only report accounts whose score changed by this much.")
def refresh(client: str, min_delta: float):
    """Recompute scores for all accounts and report changes."""
    changed = score_matrix(client, save=True)
    significant = [c for c in changed if abs((c["new_score"] or 0) - (c["old_score"] or 0)) >= min_delta]

    if not significant:
        click.echo(f"  No significant score changes (threshold: {min_delta}).")
        return

    click.echo(f"\n  Score changes for {client}:")
    click.echo(f"  {'Company':<25} {'Fit':>5} {'Old':>6} {'New':>6} {'Delta':>7} {'Status':<15} Label")
    click.echo(f"  {'-'*25} {'-'*5} {'-'*6} {'-'*6} {'-'*7} {'-'*15} {'-'*8}")
    for c in sorted(significant, key=lambda x: x["new_score"] or 0, reverse=True):
        old = c["old_score"] or 0
        new = c["new_score"] or 0
        delta = new - old
        fit = c.get("fit_score") or "—"
        fit_str = f"{fit:.1f}" if isinstance(fit, float) else fit
        label = threshold_label(new)
        click.echo(
            f"  {c['company']:<25} {fit_str:>5} {old:>6.1f} {new:>6.1f} "
            f"{'▲' if delta > 0 else '▼'}{abs(delta):>5.1f}  "
            f"{c['status']:<15} {label}"
        )


@cli.command("list")
@click.option("--client", required=True, help="Client slug.")
@click.option("--min-score", default=0.0, show_default=True)
def list_scores(client: str, min_score: float):
    """List all accounts ranked by current score."""
    accounts = get_prioritized(client, min_score=min_score)
    if not accounts:
        click.echo("  No accounts found.")
        return

    click.echo(f"\n  {'#':<4} {'Company':<25} {'Fit':>5} {'Score':>6} {'Tier':<6} {'Status':<16} {'Signal':<14} Label")
    click.echo(f"  {'-'*4} {'-'*25} {'-'*5} {'-'*6} {'-'*6} {'-'*16} {'-'*14} {'-'*6}")
    for i, a in enumerate(accounts, 1):
        score = a["current_score"]
        fit = a.get("fit_score")
        fit_str = f"{fit:.1f}" if fit is not None else "—"
        click.echo(
            f"  {i:<4} {a['company']:<25} {fit_str:>5} {score:>6.1f} "
            f"T{a.get('icp_tier', '?'):<5} {a.get('status', '?'):<16} "
            f"{a.get('why_now_signal', {}).get('type', '?'):<14} "
            f"{threshold_label(score)}"
        )


@cli.command("record-event")
@click.option("--client", required=True)
@click.option("--company", required=True)
@click.option("--event", required=True, type=click.Choice(["sentiment", "birddog_signal", "status_change"]))
@click.option("--value", required=True, help="Event value (e.g. positive, negative, new_signal).")
@click.option("--reason", default="", help="Optional note on why this event occurred.")
def record(client: str, company: str, event: str, value: str, reason: str):
    """Record a score-affecting event for one account."""
    matrix = load_client_matrix(client)
    profile = load_profile(client)
    from generate_outreach import find_account  # noqa: E402
    account = find_account(matrix, company)
    record_event(account, event_type=event, value=value, reason=reason, profile=profile)
    path = _matrix_path(client)
    path.write_text(json.dumps(matrix, indent=2) + "\n")
    click.echo(
        f"  Recorded {event}={value} for {company}. "
        f"New score: {account['current_score']} ({threshold_label(account['current_score'])})"
    )


if __name__ == "__main__":
    cli()
